name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Go core init
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: go fmt
      run:
        go fmt ./...

    - name: golint
      uses: github.com/golangci/golangci-lint
      run:
        #golangci-lint.exe run --disable=typecheck ./...

    - name: Test core
      run:
        go test -v ./...

    - name: Build
      run:
        go build -v ./...


